[[sources]] 
name = "friendly-snippets"
git = "https://github.com/rafamadriz/friendly-snippets.git"

[[sources.paths]]
scope = ["html"]
path = "snippets/html.json"


[[sources.paths]]
scope = ["go"]
path = "snippets/go.json"


[[sources.paths]]
scope = ["css"]
path = "snippets/css.json"


