# theme = "tokyonight"
# theme = "hex_lavender"
# theme = "kaolin-dark"
# theme = "github_dark_tritanopia"
# theme = "spacebones_light"
# theme = "flatwhite"
# theme = "rose_pine_dawn"
# theme = "nightfox"
# theme = "mellow"
# theme = "jetbrains_dark"
# theme = "dark_plus"
# theme = "everforest_dark"
theme = "darkvoid"
# theme = "onedarker"
# theme = "flux"

[keys.normal]
"'" = "goto_word"
tab = ":buffer-next"
S-tab = ":buffer-previous"
esc = ["collapse_selection", "keep_primary_selection"]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
x = ["goto_line_start", "select_mode", "goto_line_end_newline"]
C-6 = ["goto_last_accessed_file"]
C-h = ["jump_view_left"]
C-j = ["jump_view_down"]
C-k = ["jump_view_up"]
C-l = ["jump_view_right"]
        
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
# C-g = [":new", ":insert-output go run ~/Repositories/project-oil/main.go", ":buffer-close!", ":redraw"]
# C-g = [":new", ":insert-output gitu", ":buffer-close!", ":redraw"]

[keys.normal.q]
q = "wclose"


[keys.normal.space.b]
l = ['buffer_picker'] # Buffer picker
q = [':buffer-close!'] # Buffer close


[keys.normal.space.g]
c = "changed_file_picker"



[keys.normal.g]
# o = ["goto_definition", "goto_previous_buffer", "vsplit", "jump_backward"]
# O = ["goto_definition", "goto_previous_buffer", "hsplit", "jump_backward"]
o = ["vsplit", "goto_definition"]
O = ["hsplit", "goto_definition"]
D = ["find_prev_char",  "move_char_left", "goto_definition"]

[keys.normal.backspace]
backspace = "suspend"
c = ":buffer-close"
y = ":yank-diagnostic"

[keys.normal.space]
f = ['file_picker_in_current_directory']
F = ['file_picker_in_current_buffer_directory']
q = [":buffer-close"]
W = [":write-all"]
N = [":insert-output the-way search --stdout", ":redraw"]
T = [":new", ":insert-output eza --tree -I '*.png'"]


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor]
bufferline = "always"
idle-timeout = 50
auto-format = true
popup-border = "all"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[editor.soft-wrap]
enable = true
max-indent-retain = 0
wrap-indicator = ""
max-wrap = 25

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator"]
center = ["spinner"]
right = ["diagnostics", "selections", "file-type", "position", "position-percentage"]

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 30000
