[window]
opacity = 0.9
decorations = "none"

[cursor]
style = { shape = "Block", blinking = "Always"}
unfocused_hollow = true
blink_timeout = 0

[font]
normal.family = "CaskaydiaMono Nerd Font Mono"
size = 7

[scrolling]
history = 100000

[colors]
draw_bold_text_with_bright_colors = false

# Kanso Ink theme
[colors.primary]
background = "#14171d"
foreground = "#c5c9c7"

[colors.cursor]
text = "#14171d"
cursor = "#c5c9c7"

[colors.selection]
text = "#c5c9c7"
background = "#9E424A"

[colors.normal]
black = "#14171d"
red = "#c4746e"
green = "#8a9a7b"
yellow = "#c4b28a"
blue = "#8ba4b0"
magenta = "#a292a3"
cyan = "#8ea4a2"
white = "#a4a7a4"

[colors.bright]
black = "#5C6066"
red = "#e46876"
green = "#87a987"
yellow = "#e6c384"
blue = "#7fb4ca"
magenta = "#938aa9"
cyan = "#7aa89f"
white = "#c5c9c7"

[env]
TERM = "xterm-256color"
